#!/bin/env ruby
# encoding: utf-8
# Command-Line Music Player

# Copyright 2013  Jim Cochrane
# Command-Line Music Player is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License, verson 2,
# as published by the Free Software Foundation.  (See the LICENSE file.)

require_relative './configuration'
require_relative './player'
require_relative './optionstate'
require 'pp'

configuration = Configuration.new
opt = configuration.optionstate
if opt.cl_error
  puts opt.usage
  exit 1
end
player = Player.new
args = opt.regular_arguments
db = configuration.db
list = []
i = 0
nonmatches = []
args.each do |arg|
  l = db.matchesfor(arg)
  if l.empty?
    if ! db.db_newly_created
      nonmatches << arg
    else
      $stderr.puts "No matches found for #{arg}"
    end
  end
  list += l
end
# If some arguments did not match any files, try rebuilding the database.
if ! nonmatches.empty?
  db.append_to_database(nonmatches)
  nonmatches.each do |ptrn|
    l = db.matchesfor(ptrn)
    if l.empty?
      $stderr.puts "No matches found for #{ptrn}"
    end
    list += l
  end
end

if opt.editdb
  db.edit
  exit 0
end
if ! opt.report_only
  if list.length > 0
    player.playfiles(list)
  end
end
if opt.listfiles || opt.showinfo
  if ! opt.showinfo
    output = list.join("\n")
  else
    output = ''
    list.each do |path|
      output += "#{path}\n"
      tool = configuration.infotool
      output += tool.info_for(path)
      output += "\n"
    end
  end
  pager = ENV['PAGER'] || 'more'
  begin
    IO.popen(pager, 'w') { |f| f.puts output }
  rescue Errno::EPIPE => e
    $stderr.puts "Warning: #{pager} failed. [#{e}]" if ENV['DEBUG']
  rescue StandardError => e
    $stderr.puts "Warning: #{pager} failed. [#{e}]"
  end
end
